name: NixOS Build

on:
  workflow_run:
    workflows:
      - NixOS Flake Check
    types:
      - completed

jobs:
  configurations:
    name: Get NixOS configurations

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.configurations.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Get NixOS configurations
        id: configurations
        shell: bash
        run: |
          matrix="$(
            nix eval \
              --json \
              .#nixosConfigurations \
              --apply builtins.attrNames
          )"

          echo "Found configurations:"
          echo "$matrix"

          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.host }}

    needs:
      - configurations

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        host: ${{ fromJSON(needs.configurations.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build ${{ matrix.host }}
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --no-link \
            --show-trace
