name: NixOS Flake Check

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check NixOS Flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check flake
        run: |
          nix flake check \
            --no-build \
            --show-trace
